import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const html=readFileSync('src/index.html','utf8');
const css=readFileSync('public/assets/editorial.css','utf8');
test('versão editorial v5 identificada',()=>assert.ok(html.includes('data-editorial-version="5"')));
test('hero aprovado foi restaurado',()=>{assert.ok(html.includes('Você não precisa'));assert.ok(html.includes('/assets/atividade-profissional.jpg'));assert.ok(html.includes('Quero conhecer a avaliação'));});
test('hero mantém autoridade sem prometer atendimento pessoal',()=>{const hero=html.slice(html.indexOf('id="inicio"'),html.indexOf('id="atendimento"'));assert.ok(hero.includes('Dra. Elizete Kaffer'));assert.ok(!hero.includes('consulta pessoal com a doutora'));});
test('oferta continua logo após a abertura',()=>assert.ok(html.indexOf('id="atendimento"')<html.indexOf('id="sinais"')));
test('pilares e frentes práticas permanecem na página',()=>{for(const word of ['HÁBITOS','CUIDADOS EM CASA','SERVIÇOS NA CLÍNICA','Remoção, Reposição e Reabilitação']) assert.ok(html.includes(word));});
test('imagens são tratadas como fundo integrado nas seções principais',()=>{for(const cls of ['resources-backdrop','journey-backdrop','authority-background'])assert.ok(html.includes(cls));});
test('v5 remove máscaras orgânicas e cantos aleatórios',()=>{assert.ok(css.includes('V5 remove deliberadamente'));assert.ok(css.includes('.resources-v5 *, .journey-v5 *, .authority-v5 *{border-radius:0}'));});
