import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const html=readFileSync('src/index.html','utf8');
const js=readFileSync('src/main.js','utf8');
const editorial=readFileSync('public/assets/editorial.js','utf8');
const css=readFileSync('public/assets/editorial.css','utf8');
const vercel=JSON.parse(readFileSync('vercel.json','utf8'));
test('primeira dobra usa fotografia integrada da doutora',()=>{const hero=html.slice(html.indexOf('id="inicio"'),html.indexOf('id="atendimento"'));assert.ok(hero.includes('hero-photo-v5'));assert.ok(hero.includes('/assets/atividade-profissional.jpg'));assert.ok(hero.includes('hero-shade-v5'));});
test('recursos são linhas sobre imagem integrada, não grade de cards fotográficos',()=>{assert.ok(html.includes('resources-lines'));assert.ok(!html.includes('class="exam"'));});
test('autoridade usa novo acervo de mentoria como fundo',()=>assert.ok(html.includes('/assets/dra-elizete-mentora.jpg')));
test('retorno continua explícito e sem preço',()=>{assert.ok(html.includes('O retorno incluído não depende'));assert.ok(!/R\$/.test(html));});
test('scroll e parallax são implementados com redução de movimento',()=>{assert.ok(editorial.includes('updateParallax'));assert.ok(editorial.includes('scroll-reveal'));assert.ok(css.includes('prefers-reduced-motion'));});
test('botões e X possuem microinterações',()=>{assert.ok(css.includes('.button:hover .arrow'));assert.ok(css.includes('.close-dialog:hover'));});
test('YouTube continua sob clique',()=>{assert.ok(!html.includes('<iframe'));assert.ok(html.includes('id="play-video"'));assert.ok(js.includes('youtube-nocookie.com/embed/euDugEHasYg'));});
test('CSP continua sem unsafe-inline',()=>{const policy=vercel.headers.flatMap(x=>x.headers).find(x=>x.key==='Content-Security-Policy').value;assert.ok(!policy.includes("'unsafe-inline'"));});
