/** One-time, idempotent editorial upgrade. Preserves the project and existing assets. */
import {readFile,writeFile} from 'node:fs/promises';
const path='src/index.html';let html=await readFile(path,'utf8');
if(html.includes('data-editorial-version="3"')){console.log('Editorial v3 já aplicado.');process.exit(0);}
const before=html;
const hero=`<section class="hero-shell editorial-hero" id="inicio" aria-labelledby="hero-title" data-editorial-version="3">
<div class="wrap editorial-hero-grid"><div class="hero-copy"><p class="eyebrow">SAÚDE SHALON · CAMPINAS, SP</p><p class="hero-category">Centro Terapêutico Avançado</p><h1 id="hero-title">Quando o mal-estar persiste,<br> <em>seu caso merece atenção por inteiro.</em></h1><p class="hero-description">Avaliação presencial de 2 a 3 horas, análise de 800 parâmetros e consulta explicativa, com <strong>retorno incluído.</strong></p><p class="hero-method">Conheça o atendimento orientado pela<br><strong>Metodologia Dra. Elizete Kaffer.</strong></p><a class="button button-primary contact-link" href="{{WHATSAPP_URL}}" data-placement="hero"><svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 11.7a8.5 8.5 0 0 1-12.6 7.5L3 20.5l1.3-4.7a8.5 8.5 0 1 1 16.2-4.1Z"/><path d="M8 8c1 4 4 7 8 8"/><path d="m8 8 2 2-1 1m7 5-2-2-1 1"/></svg><span>Falar com a equipe no WhatsApp</span><span class="arrow" aria-hidden="true">↗</span></a><p class="microcopy">Atendimento particular. Informações e agendamento pelo WhatsApp.</p><a class="text-link hero-explore" href="#atendimento">Veja o que está incluído <span aria-hidden="true">↓</span></a></div><figure class="editorial-visual"><div class="hero-photo"><img src="/assets/avaliacao.jpg" alt="Registro do acervo institucional: uma avaliação em andamento, com profissional, pessoa atendida e equipamentos." width="1600" height="900" fetchpriority="high"></div><figcaption><span>DA AVALIAÇÃO AO RETORNO</span><p>Tempo para avaliar.<br><strong>Clareza para seguir.</strong></p><a href="#jornada" aria-label="Conheça as etapas do atendimento"><span aria-hidden="true">↗</span></a></figcaption></figure></div><div class="wrap hero-footer-line"><p>Uma equipe para receber você.<br>Uma metodologia para orientar o cuidado.</p><span>AVALIAR · ORIENTAR · ACOMPANHAR</span></div></section>`;
html=html.replace(/<section class="hero-shell"[\s\S]*?<\/section>/,hero);
if(html===before)throw new Error('Estrutura do hero mudou; revisão manual necessária.');
const offer=html.match(/<section class="[^"\n]*" id="atendimento"[\s\S]*?<\/section>/);
if(!offer)throw new Error('Seção de atendimento não encontrada.');
html=html.replace(offer[0],'').replace(hero,hero+'\n'+offer[0]);
html=html.replace('Comece pela avaliação.<br><em>Com retorno já incluído.</em>','Seu primeiro atendimento.<br><em>Com retorno já incluído.</em>');
const method=`<section class="root-section section-space" id="metodo" aria-labelledby="root-title"><div class="wrap method-editorial"><div><p class="eyebrow light">METODOLOGIA DRA. ELIZETE KAFFER</p><h2 id="root-title">Avaliar é o começo.<br><em>Orientar é dar direção.</em></h2><p class="section-lead">A proposta conecta as informações da avaliação a explicações e orientações para os próximos passos do cuidado.</p><p class="method-note">As orientações podem envolver três frentes, de acordo com o atendimento e a indicação profissional.</p></div><div class="care-path"><article><span class="path-number">01</span><div><p class="small-label">HÁBITOS</p><h3>O cuidado na sua rotina.</h3><p>Orientações relacionadas ao estilo de vida e aos hábitos do dia a dia.</p></div></article><article><span class="path-number">02</span><div><p class="small-label">CUIDADOS EM CASA</p><h3>A continuidade fora da clínica.</h3><p>Cuidados e eventuais produtos de uso domiciliar, quando indicados. Produtos são contratados separadamente.</p></div></article><article><span class="path-number">03</span><div><p class="small-label">SERVIÇOS NA CLÍNICA</p><h3>Recursos dentro de um plano.</h3><p>Recursos terapêuticos apresentados conforme o plano proposto e a atuação de cada profissional.</p></div></article></div></div><div class="wrap method-bottom"><span>PRIMEIRO, COMPREENDER O ATENDIMENTO.</span><p>O atendimento inicial vem primeiro.<br>A continuidade em protocolos é uma decisão posterior.</p></div></section>`;
html=html.replace(/<section class="root-section[\s\S]*?<\/section>/,method).replace(/<section class="section-space pillars-section"[\s\S]*?<\/section>/,'');
html=html.replace('<div class="people-picture"><img src="/assets/atividade-profissional.jpg" alt="Registro institucional da Dra. Elizete Kaffer em atividade profissional." width="1600" height="1067" loading="lazy">','<div class="people-picture"><img src="/assets/dra-elizete.webp" alt="Retrato institucional da Dra. Elizete Kaffer, criadora da metodologia." width="1248" height="1248" loading="lazy">');
html=html.replace('<a href="#metodo">Nosso olhar</a>','<a href="#atendimento">O atendimento</a><a href="#metodo">O método</a>');
html=html.replace('<link rel="stylesheet" href="/assets/styles.css">','<link rel="stylesheet" href="/assets/styles.css"><link rel="stylesheet" href="/assets/editorial.css"><script type="module" src="/assets/editorial.js"></script>');
html=html.replace('<span>Prévia de revisão · nova experiência</span>','<span>Saúde Shalon · prévia para aprovação</span>');
html=html.replace('<li>Validar o texto clínico, a oferta e as responsabilidades profissionais.</li>','<li>Validar o texto clínico, a oferta e as responsabilidades profissionais. Os pilares Remoção, Reposição e Reabilitação permanecem reservados para explicação técnica validada.</li>');
html=html.replace('<li>Adicionar somente depoimentos originais com autorização. Nenhum relato foi inventado.</li>','<li>Reservado: depoimento real autorizado sobre acolhimento e clareza da avaliação.</li><li>Reservado: depoimento real autorizado sobre retorno e orientações. Nenhum relato foi inventado.</li>');
await writeFile(path,html);console.log('Editorial v3 aplicado: hero branco, oferta em segunda seção, método e tipografia revisados.');
